### ISSUE TITLE
Getting PI_ERROR_OUT_OF_RESOURCES -- resolved

### ISSUE THREAD

**Issue by gbertulf** [intel-analytics/ipex-llm#10597]
Using merged from https://github.com/intel-analytics/ipex-llm/pull/10558 , I retried the 2 GPU execution on an ATSM1 x8 cards system (specs listed here -- https://wiki.ith.intel.com/display/MediaWiki/Flex-170x8+%28Inspur+-+ICX%29+Qualification)

git cloned - https://github.com/intel-analytics/ipex-llm

I ran the default script under   **../ipex-llm/python/llm/example/GPU/Deepspeed-AutoTP** 

(run_llama2_70b_pvc_1550_1_card.sh)
export ZE_AFFINITY_MASK="0,1" # specify the used GPU
NUM_GPUS=2 # number of used GPU
export MASTER_ADDR=127.0.0.1
export FI_PROVIDER=tcp
export CCL_ATL_TRANSPORT=ofi
export CCL_ZE_IPC_EXCHANGE=sockets

export LD_PRELOAD=${LD_PRELOAD}:${CONDA_PREFIX}/lib/libtcmalloc.so:${LD_PRELOAD}
basekit_root=/opt/intel/oneapi
source $basekit_root/setvars.sh --force
source $basekit_root/ccl/latest/env/vars.sh --force

export OMP_NUM_THREADS=$((56/$NUM_GPUS))
export SYCL_PI_LEVEL_ZERO_USE_IMMEDIATE_COMMANDLISTS=2
export TORCH_LLM_ALLREDUCE=1
mpirun -np $NUM_GPUS --prepend-rank \
    python deepspeed_autotp.py --repo-id-or-model-path 'meta-llama/Llama-2-70b-chat-hf' --low-bit 'sym_int4'

Execution completed with this error -- 
![image](https://github.com/intel-analytics/ipex-llm/assets/73611412/ec080697-5b62-4177-9ce7-ab249db2f404)

**Comment by plusbang** [comment]
Hi, memory size of one Flex 170 is only 16GB, therefore, it's quite reasonable that you encountered `PI_ERROR_OUT_OF_RESOURCES` (which means out of memory) when tried to use two Flex170 to run Llama-2-70b-chat-hf.

Considering the memory size, you could try to run this script(https://github.com/intel-analytics/ipex-llm/blob/main/python/llm/example/GPU/Deepspeed-AutoTP/run_vicuna_33b_arc_2_card.sh) to start instead.

**Comment by gbertulf** [comment]
Hi, thank you for the guidance. I tried the recommended script. This is a screenshot of the execution--
![image](https://github.com/intel-analytics/ipex-llm/assets/73611412/d7168213-e3be-4741-9f38-d6d92ae3edda)
![image](https://github.com/intel-analytics/ipex-llm/assets/73611412/c50c428f-3086-4277-bb2b-14b3016456f6)

Is the bad termination an expected behavior for now?
![image](https://github.com/intel-analytics/ipex-llm/assets/73611412/c47becd0-b8e6-4077-9fe6-73eff70df183)

**Comment by gbertulf** [comment]
On another note, the original intent was to try the 2-gpu environment with llama2-7b-chat-hf, i tried to swap the model in the run_vicuna_33b_arc_2_card_mod.sh script --
![image](https://github.com/intel-analytics/ipex-llm/assets/73611412/8160ebac-6878-4e31-bfae-127c4ad0b5f6)

but getting an error during execution, would you know how i can resolve the error?
![image](https://github.com/intel-analytics/ipex-llm/assets/73611412/c9a1790d-da72-4d52-8cca-7c07024c4583)
![image](https://github.com/intel-analytics/ipex-llm/assets/73611412/211c8191-2a98-4c24-a0af-b1f2e132cc42)

**Comment by gbertulf** [comment]
Thank you for this guidance. Please see my updates and further comments in the ticket.
Note, will be setting up a debug call and sending an invite shortly.

Regards,

Glen

**Comment by plusbang** [comment]
> Is the bad termination an expected behavior for now? ![image](https://private-user-images.githubusercontent.com/73611412/318525947-c47becd0-b8e6-4077-9fe6-73eff70df183.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzAyOTAsIm5iZiI6MTcxMjAyOTk5MCwicGF0aCI6Ii83MzYxMTQxMi8zMTg1MjU5NDctYzQ3YmVjZDAtYjhlNi00MDc3LTlmZTYtNzNlZmY3MGRmMTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAzNTMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMDk5MGIwOTQ4NTVjZGExZDAxYzZjOTM3MzhkZGE3OGUxZGZiMDI5MzAzZDliNTFkMzc0ZTdiNjY0OWIzNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GetmWr6LyelNgsZAJ_9e6MYcYfcIpdBUfBUOa9kDiKM)

Yes, please refer to here for details about [the known issue](https://github.com/intel-analytics/ipex-llm/tree/main/python/llm/example/GPU/Deepspeed-AutoTP#known-issue)

**Comment by gbertulf** [comment]
This issue is resolved with some adjustments 

1) Using this script -- run_vicuna_33b_arc_2_card.sh

**Due to system constraints, this script was recommended for flex executions. Please see previous comments by dev.

2) For Latency calculations -- I applied recommended BKM from https://github.com/intel-analytics/ipex-llm/blob/main/python/llm/dev/benchmark/README.md

![image](https://github.com/intel-analytics/ipex-llm/assets/73611412/8c6805f2-db32-4e7c-95fe-e574ce70111d)
![image](https://github.com/intel-analytics/ipex-llm/assets/73611412/926f6110-34e9-46fa-8b32-bbe9254e02f2)

**Comment by gbertulf** [comment]
Issue is resolved. Closing this ticket. Thank you team for your help.
