### ISSUE TITLE
Got ZE_RESULT_ERROR_INVALID_ARGUMENT error during running Qwen2.5-Coder-3B-Instruct on npu

### ISSUE THREAD

**Issue by rsj123** [intel-analytics/ipex-llm#12548]
I am trying to run Qwen2.5-Coder-3B-Instruct on npu
The running command is `python qwen.py --repo-id-or-model-path "Qwen/Qwen2.5-Coder-3B-Instruct" --save-directory E:\llm\models\Qwen2.5-Coder-3B-Instruct-low-bit`

But I got an error `ZE_RESULT_ERROR_INVALID_ARGUMENT`
The full log:
```
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.63s/it]
2024-12-14 04:31:56,001 - INFO - Converting model, it may takes up to several minutes ...
2024-12-14 04:32:12,330 - INFO - Finish to convert model
decode start compiling
decode end compiling
Model saved to E:\llm\models\Qwen2.5-Coder-3B-Instruct-low-bit\decoder_layer_0.xml
decode start compiling
decode end compiling
Model saved to E:\llm\models\Qwen2.5-Coder-3B-Instruct-low-bit\decoder_layer_1.xml
prefill start compiling
prefill end compiling
Model saved to E:\llm\models\Qwen2.5-Coder-3B-Instruct-low-bit\decoder_layer_prefill.xml
Traceback (most recent call last):
  File "E:\llm\ipex-llm\python\llm\example\NPU\HF-Transformers-AutoModels\LLM\qwen.py", line 61, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "C:\Users\31092\AppData\Local\Programs\Python\Python310\lib\unittest\mock.py", line 1379, in patched
    return func(*newargs, **newkeywargs)
  File "C:\Users\31092\AppData\Local\Programs\Python\Python310\lib\site-packages\ipex_llm\transformers\npu_model.py", line 238, in from_pretrained
    model = cls.optimize_npu_model(*args, **optimize_kwargs)
  File "C:\Users\31092\AppData\Local\Programs\Python\Python310\lib\site-packages\ipex_llm\transformers\npu_model.py", line 308, in optimize_npu_model
    optimize_llm_single_process(
  File "C:\Users\31092\AppData\Local\Programs\Python\Python310\lib\site-packages\ipex_llm\transformers\npu_models\convert.py", line 457, in optimize_llm_single_process
    convert_llm(model,
  File "C:\Users\31092\AppData\Local\Programs\Python\Python310\lib\site-packages\ipex_llm\transformers\npu_pipeline_model\convert_pipeline.py", line 213, in convert_llm
    convert_llm_for_deploy(model,
  File "C:\Users\31092\AppData\Local\Programs\Python\Python310\lib\site-packages\ipex_llm\transformers\npu_pipeline_model\convert_pipeline.py", line 481, in convert_llm_for_deploy
    convert_qwen_layer(model, 0, n_splits_linear, n_splits_down_proj,
  File "C:\Users\31092\AppData\Local\Programs\Python\Python310\lib\site-packages\ipex_llm\transformers\npu_pipeline_model\qwen.py", line 200, in convert_qwen_layer
    rest_blob_path = update_names_of_IR_and_export_blob(single_decoder,
  File "C:\Users\31092\AppData\Local\Programs\Python\Python310\lib\site-packages\ipex_llm\transformers\npu_pipeline_model\common.py", line 59, in update_names_of_IR_and_export_blob
    compiledModel = core.compile_model(model, device_name="NPU")
  File "C:\Users\31092\AppData\Local\Programs\Python\Python310\lib\site-packages\intel_npu_acceleration_library\backend\..\external\openvino\runtime\ie_api.py", line 543, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src/inference/src/cpp/core.cpp:107:
Exception from src/inference/src/dev/plugin.cpp:53:
Exception from src/plugins/intel_npu/src/plugin/src/plugin.cpp:697:
Exception from src/plugins/intel_npu/src/plugin/src/compiled_model.cpp:62:
Exception from src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp:853:
L0 pfnCreate2 result: ZE_RESULT_ERROR_INVALID_ARGUMENT, code 0x78000004
```

**Comment by plusbang** [comment]
Hi, @rsj123 

Could you please provide more details about the hardware (e.g., MTL or LNL, specific CPU model), NPU driver version, and dependencies?

**Comment by dockerg** [comment]
> Hi, @rsj123
> 
> Could you please provide more details about the hardware (e.g., MTL or LNL, specific CPU model), NPU driver version, and dependencies?

The same issue is occurred with 226V in my side, but when i use 258V to retry, the issue does not occur

**Comment by plusbang** [comment]
> The same issue is occurred with 226V in my side, but when i use 258V to retry, the issue does not occur

Hi, to avoid the issue on 226V, please try to `set IPEX_LLM_NPU_DISABLE_COMPILE_OPT=1`.

**Comment by rsj123** [comment]
> Hi, @rsj123
> 
> Could you please provide more details about the hardware (e.g., MTL or LNL, specific CPU model), NPU driver version, and dependencies?

Hi, I am using ultra7 155H on laptop

**Comment by plusbang** [comment]
> 
> Hi, I am using ultra7 155H on laptop, npu driver version is 32.0.100.2540

Please refer to our doc (https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/npu_quickstart.md) for details.

Need to update NPU driver to `32.0.100.3104`, and runtime configuration `set IPEX_LLM_NPU_MTL=1` is required.

**Comment by rsj123** [comment]
> > Hi, I am using ultra7 155H on laptop, npu driver version is 32.0.100.2540
> 
> Please refer to our doc (https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/npu_quickstart.md) for details.
> 
> Need to update NPU driver to `32.0.100.3104`, and runtime configuration `set IPEX_LLM_NPU_MTL=1` is required.

Thanks for your help, I think I found the reason:
- First I upgraded the drivers (not sure if that was a contributing factor)
- I'm running in a windows terminal so I need to set the environment variable using `$env:IPEX_LLM_NPU_MTL=1`

**Comment by Martin-HZK** [comment]
> > Hi, I am using ultra7 155H on laptop, npu driver version is 32.0.100.2540
> 
> Please refer to our doc (https://github.com/intel-analytics/ipex-llm/blob/main/docs/mddocs/Quickstart/npu_quickstart.md) for details.
> 
> Need to update NPU driver to `32.0.100.3104`, and runtime configuration `set IPEX_LLM_NPU_MTL=1` is required.

I am not sure why is the driver version closely related to the model conversion?

**Comment by syheliel** [comment]
@Martin-HZK OpenVINO relies on the support of the NPU driver. ver. 32.0.100.3104 add support for OpenVINO 2024.4 and fix certain compilation problem. You can check [NPU_Win_Release_Notes_v3104.pdf](https://downloadmirror.intel.com/838895/NPU_Win_Release_Notes_v3104.pdf)
