### ISSUE TITLE
RuntimeError: Build program log for 'Intel(R) Arc(TM) 140V GPU (16GB)': -11 (PI_ERROR_BUILD_PROGRAM_FAILURE)

### ISSUE THREAD

**Issue by johnysh** [intel-analytics/ipex-llm#12601]
Platform: LNL
OS: Win11
Pip list : [lnl_piplist.txt](https://github.com/user-attachments/files/18236315/lnl_piplist.txt)

We upgraded ipex-llm using pip install --pre --upgrade ipex-llm[xpu_lnl] --extra-index-url https://pytorch-extension.intel.com/release-whl/stable/lnl/cn/ to run Qwen1.5-1.8B models , but met runtime error as title. log as below:

```
C:\Users\zenbook\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\transformers\deepspeed.py:24: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
SYCL_ENABLE_DEFAULT_CONTEXTS=1
SYCL_CACHE_PERSISTENT=1
IPEX_LLM_LOW_MEM=1
2024-12-24 09:17:26,969 - INFO - Converting the current model to sym_int4 format......
C:\Users\zenbook\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\torch\nn\init.py:452: UserWarning: Initializing zero-element tensors is a no-op
  warnings.warn("Initializing zero-element tensors is a no-op")
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[1], line 39
     37 input_ids = tokenizer.encode(prompt, return_tensors="pt").to('xpu')
     38 st = time.time()
---> 39 output = model.generate(input_ids,
     40                         max_new_tokens=n_predict)
     41 torch.xpu.synchronize()
     42 end = time.time()

File ~\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\torch\utils\_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\ipex_llm\transformers\lookup.py:125, in generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, **kwargs)
    113             logger.warning("Since you call the generate with lookahead parameter, "
    114                            f"Speculative decoding parameters {spec_params} are "
    115                            "removed in the generation.")
    116         return self.lookup_generate(inputs=inputs,
    117                                     num_output_tokens=lookahead,
    118                                     generation_config=generation_config,
   (...)
    122                                     prefix_allowed_tokens_fn=prefix_allowed_tokens_fn,
    123                                     **kwargs)
--> 125 return original_generate(self,
    126                          inputs=inputs,
    127                          generation_config=generation_config,
    128                          logits_processor=logits_processor,
    129                          stopping_criteria=stopping_criteria,
    130                          prefix_allowed_tokens_fn=prefix_allowed_tokens_fn,
    131                          synced_gpus=synced_gpus,
    132                          assistant_model=assistant_model,
    133                          streamer=streamer,
    134                          **kwargs)

File ~\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\torch\utils\_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\ipex_llm\transformers\speculative.py:127, in generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, **kwargs)
    123 for var in ['max_step_draft', 'th_stop_draft', 'hf_adjust',
    124             'auto_th_stop_draft', 'auto_parameters', 'min_step_draft',
    125             'th_batch_num']:
    126     kwargs.pop(var, None)
--> 127 return original_generate(self,
    128                          inputs=inputs,
    129                          generation_config=generation_config,
    130                          logits_processor=logits_processor,
    131                          stopping_criteria=stopping_criteria,
    132                          prefix_allowed_tokens_fn=prefix_allowed_tokens_fn,
    133                          synced_gpus=synced_gpus,
    134                          assistant_model=assistant_model,
    135                          streamer=streamer,
    136                          **kwargs)

File ~\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\torch\utils\_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\ipex_llm\transformers\pipeline_parallel.py:283, in generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, **kwargs)
    276         max_new_tokens = kwargs.pop("max_new_tokens", None)
    278     return self.pipeline_parallel_generate(inputs=inputs,
    279                                            max_new_tokens=max_new_tokens,
    280                                            generation_config=generation_config,
    281                                            **kwargs)
--> 283 return original_generate(self,
    284                          inputs=inputs,
    285                          generation_config=generation_config,
    286                          logits_processor=logits_processor,
    287                          stopping_criteria=stopping_criteria,
    288                          prefix_allowed_tokens_fn=prefix_allowed_tokens_fn,
    289                          synced_gpus=synced_gpus,
    290                          assistant_model=assistant_model,
    291                          streamer=streamer,
    292                          negative_prompt_ids=negative_prompt_ids,
    293                          negative_prompt_attention_mask=negative_prompt_attention_mask,
    294                          **kwargs)

File ~\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\torch\utils\_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\transformers\generation\utils.py:1701, in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, **kwargs)
   1698 batch_size = inputs_tensor.shape[0]
   1700 device = inputs_tensor.device
-> 1701 self._prepare_special_tokens(generation_config, kwargs_has_attention_mask, device=device)
   1703 # decoder-only models must use left-padding for batched generation.
   1704 if not self.config.is_encoder_decoder and not is_torchdynamo_compiling():
   1705     # If `input_ids` was given, check if the last id in any sequence is `pad_token_id`
   1706     # Note: If using, `inputs_embeds` this check does not work, because we want to be more hands-off.

File ~\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\transformers\generation\utils.py:1545, in GenerationMixin._prepare_special_tokens(self, generation_config, kwargs_has_attention_mask, device)
   1542     logger.warning(f"Setting `pad_token_id` to `eos_token_id`:{pad_token_tensor} for open-end generation.")
   1544 # we can't infer attn mask if pad token is set to be eos token in model's generation config
-> 1545 if eos_token_tensor is not None and pad_token_tensor in eos_token_tensor:
   1546     if kwargs_has_attention_mask is not None and not kwargs_has_attention_mask:
   1547         logger.warning_once(
   1548             "The attention mask is not set and cannot be inferred from input because pad token is same as eos token."
   1549             "As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` "
   1550             "to obtain reliable results."
   1551         )

File ~\.miniconda_dev_zone\envs\notebook-zone\Lib\site-packages\torch\_tensor.py:1116, in Tensor.__contains__(self, element)
   1111     return handle_torch_function(Tensor.__contains__, (self,), self, element)
   1112 if isinstance(
   1113     element, (torch.Tensor, Number, torch.SymInt, torch.SymFloat, torch.SymBool)
   1114 ):
   1115     # type hint doesn't understand the __contains__ result array
-> 1116     return (element == self).any().item()  # type: ignore[union-attr]
   1118 raise RuntimeError(
   1119     f"Tensor.__contains__ only supports Tensor or scalar, but you passed in a {type(element)}."
   1120 )

RuntimeError: The program was built for 1 devices
Build program log for 'Intel(R) Arc(TM) 140V GPU (16GB)':
-11 (PI_ERROR_BUILD_PROGRAM_FAILURE)
 ```

**Comment by hkvision** [comment]
Hi I suppose this is an issue due to transformers versions. In your pip list, I find your transformers is 4.43.2, can you switch the default transformers version we support 4.37.0 to have another try?

**Comment by johnysh** [comment]
Hi  , I tried transformers==4.37.0 , but still met the same error.

***@***.***

**Comment by johnysh** [comment]
Thanks Yuwen， issue is fixed， pls close it
